### ISSUE TITLE
Mod portal deprecation reason

### ISSUE THREAD

**Issue by AllenJB** [Quezler/factorio__mod--ltn-rich-text-converter#1]
Hi,

Thank you for this mod, I've been using it without any noticeable issues (tho I admittedly haven't been doing anything complex with my LTN setups).

When I went to recommend it to others asking how to achieve this, I noticed it's been marked deprecated on the mod portal. What's the reason for this? Is there a bug / technical issue? Or personal reasons (eg. you no longer have enough time to maintain it)? (I don't want to know the exact reason if personal, but knowing of any technical issues would be useful)

**Comment by Quezler** [comment]
![Screenshot_20220522-053802.png](https://user-images.githubusercontent.com/3179271/169677334-c30c20ac-180e-4ecc-8477-971bd7831d80.png)
